spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect # 设置 innoDB 引擎
  datasource:
    url: jdbc:mysql://localhost:3306/security_db
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
